class ValidCode:
    VALID_INDUSTRY_CODES = [
        "REAL_ESTATE",
        "CONSTRUCTION",
        "FOOD_MANUFACTURING",
        "COSMETICS_MANUFACTURING",
        "ELECTRONICS_MANUFACTURING",
        "PRECISION_MANUFACTURING",
        "AUTOMOTIVE_MANUFACTURING",
        "FASHION_MANUFACTURING",
        "B2C_MANUFACTURING",
        "B2B_MANUFACTURING",
        "LOGISTICS",
        "IT_COMMUNICATIONS",
        "CONTRACT_DEVELOPMENT",
        "RETAIL",
        "WHOLESALE",
        "FINANCE",
        "HOSPITALITY",
        "CONSULTING",
        "HEALTHCARE",
        "ADVERTISING",
        "ENTERTAINMENT",
        "EDUCATION",
        "MEDIA",
        "OTHER",
    ]

    VALID_EMPLOYEE_SIZE_CODES = [
        "INDIVIDUAL",
        "EXTRA_SMALL",
        "SMALL",
        "MEDIUM",
        "EXTRA_MEDIUM",
        "LARGE",
        "EXTRA_LARGE",
        "HUGE",
        "EXTRA_HUGE",
    ]

    VALID_REVENUE_CODES = [
        "TINY",
        "EXTRA_TINY",
        "SMALL",
        "EXTRA_SMALL",
        "MEDIUM",
        "EXTRA_MEDIUM",
        "LARGE",
        "EXTRA_LARGE",
        "HUGE",
        "EXTRA_HUGE",
    ]

    VALID_JOB_TYPE_CODES = [
        "EXECUTIVES",
        "PR",
        "MARKETING",
        "INSIDE_SALES",
        "FIELD_SALES",
        "IT",
        "ACCOUNTING",
        "CUSTOMER_SUPPORT",
        "RESEARCH_TECH",
        "OTHER",
    ]

    VALID_POSITION_CODES = [
        "CEO",
        "DIRECTOR",
        "HEAD_DEPARTMENT",
        "MANAGER",
        "LEADER",
        "EMPLOYEE",
        "OUTSOURCING",
    ]

    VALID_PREFECTURE_CODES = [
        "HOKKAIDO",
        "AOMORI",
        "IWATE",
        "MIYAGI",
        "AKITA",
        "YAMAGATA",
        "FUKUSHIMA",
        "IBARAKI",
        "TOCHIGI",
        "GUNMA",
        "SAITAMA",
        "CHIBA",
        "TOKYO",
        "KANAGAWA",
        "NIIGATA",
        "TOYAMA",
        "ISHIKAWA",
        "FUKUI",
        "YAMANASHI",
        "NAGANO",
        "GIFU",
        "SHIZUOKA",
        "AICHI",
        "MIE",
        "SHIGA",
        "KYOTO",
        "OSAKA",
        "HYOGO",
        "NARA",
        "WAKAYAMA",
        "TOTTORI",
        "SHIMANE",
        "OKAYAMA",
        "HIROSHIMA",
        "YAMAGUCHI",
        "TOKUSHIMA",
        "KAGAWA",
        "EHIME",
        "KOCHI",
        "FUKUOKA",
        "SAGA",
        "NAGASAKI",
        "KUMAMOTO",
        "OITA",
        "MIYAZAKI",
        "KAGOSHIMA",
        "OKINAWA",
    ]
