services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./backend:/workspace/backend:cached
    ports:
      - 8000:8000

    restart: always

    depends_on:
      - db

    env_file:
      - ./backend/.env

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  postgres-data:

networks:
  default:
    name: itss-network
