"""update_user_table

Revision ID: 65771c11e39d
Revises: ef684af1dd29
Create Date: 2024-12-23 00:54:39.671907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65771c11e39d'
down_revision: Union[str, None] = 'ef684af1dd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'restaurant')
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.add_column('dishes', sa.Column('restaurant', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
